### PR TITLE
First cut at a Meson build to create shared and static libraries locally

### PR DESCRIPTION
**Pull request by russel**
Whilst Dub is the standard path for D packages and modules, it can be very useful the get things packaged for the distributions directly. cf. GtkD. This gets shared (and static) libraries on the systems for all to use. With a view to moving toward getting someone (*) to package dinotify for Debian and Fedora, here is the beginnings of a Meson build. It seems to work for me just now.

(*) Preferably the people that package GtkD for Debian and Fedora.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Looks good and passes test on latest master.

Also - Meson looks kind of nice, but I never used it.
What's your assesment is it worth the trouble to migrate from SCons (for my other projects)?

**Comment by russel** [comment]
I think for any platform supported by Meson, Meson is far, far superior to CMake. That I have to use CMake at all now is that I use CLion – I was going to try and look at the CMake support for D but the person owning the repository seems uncommunicative regarding the problems it has. I still often use both Meson and SCons. For the moment for D projects Meson is fine as long as there are no dependencies required from the Dub repository, i.e. it assumes all dependencies have a pkgconfig file to work with locally installed libraries. For this is is probably better than SCons. However I am working on a tool for SCons to do Dub repository fetches and builds. So I think SCons has a future to be competition for Dub as a build system. Whether to migrate from SCons to Meson has to be on per project basis. Currently I am using both depending.

**Comment by russel** [comment]
@DmitryOlshansky I forgot to mention earlier a crucial Meson/SCons issue: for the moment Meson cannot do unity builds for D, whereas SCons can (ProgramAllAtOnce builder). This becomes critical when using unit-threaded for testing as it required unity builds.

**Comment by DmitryOlshansky** [comment]
> whereas SCons can (ProgramAllAtOnce builder). 

Is that all in upstream SCons or do I need some custom build?

Overall - cool stuff. If you have any problem or feedback on this project (or any actually) you may also mail me directly to dmitry at olshansky dot me.

**Comment by russel** [comment]
ProgramAllAtOnce is in the dmd, ldc, and gdc tools definitely in SCons 3.0.0, but I think it was also in 2.6.? SCons 3.0.0 runs on Python 3 so is the one true SCons. :-) The big thing I haven't merged is the dub tool, which isn't really a fit state to merge. I must get back to this using knowledge from building with Meson rather than Dub. I'm russel at winder dot org dot uk.

**Pull request merged**
